import 'package:flutter/material.dart';

const PRIMARY_BROWN_COLOR = Color(0xFFAC6122);
const PRIMARY_ORANGE_COLOR = Color(0xFFDD8037);
const PRIMARY_YELLOW_COLOR = Color(0xFFFCCE8A);
const PRIMARY_DARK_COLOR = Color(0xFF853C0D);



const HOME_COLOR = Color(0xA0DD8037);

const BACKGROUND_YELLOW_COLOR = Color(0xFFF7CA89);

const CURSOR_COLOR = Color(0xFF241E17);
const BORDER_COLOR = Color(0xFF575757);

const DARK_PRIMARY_COLOR = Color(0xFF353535);
const GREY_PRIMARY_COLOR = Color(0xFF747474);
const GREY_SHALLOW_COLOR = Color(0xFF9D9D9D);

const WHITE_LIGHT1_COLOR = Color(0xFFFAFAFA);
const WHITE_LIGHT2_COLOR = Color(0xFFE8E8E8);
const WHITE_LIGHT3_COLOR = Color(0xFFDFDFDF);
const WHITE_LIGHT4_COLOR = Color(0xFFD7D7D7);

const WHITE_GREY_COLOR = Color(0xFF0D0D0D);

const BG_COLOR = Color(0xFFF3F3F3);
