import 'dart:io';

const ACCESS_TOKEN_KEY = 'ACCESS_TOKEN';
const REFRESH_TOKEN_KEY = 'REFRESH_TOKEN';

final ip = '3.37.179.100:8080';


const GOOGLE_API_KEY = 'AIzaSyBF6vHW7S9rO17wZo_ooVCgFKyCx29VUAg';